require("dotenv").config();
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const userRoutes = require("./routes/userRoutes");
const articleRoutes = require("./routes/articleRoutes");
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use("/users", userRoutes);
app.use("/articles", articleRoutes);
module.exports = app;
